image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info "-Dselenide.headless=true"  # запускаем тест, флаг --info позволяет выводить больше информации и стартуем Selenide в Headless-режиме

